# Generated by Django 5.0 on 2024-01-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bood_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personcard",
            name="target",
            field=models.CharField(
                blank=True,
                choices=[("keep", "Поддержание формы"), ("lose", "Похудение"), ("gain", "Набор веса")],
                default="",
                max_length=4,
                verbose_name="Цель",
            ),
        ),
    ]
